### ISSUE TITLE
Project Outline - Features

### ISSUE THREAD

**Issue by r-spell** [Josephstegall/liftoff-assignments#2]
Please format the features so that it is easier to read. Also please write the features as user stories. 

See the examples in the Assignment.  Instead of "User login" they have "User login: Users will be able to create accounts and log in to the application. Each user will have a profile page."

This will help you to better see how much work each feature can be, also! 

You have so many cool ideas here, but it may be good to cut things down a bit so that you can finish within the 8-weeks. 

Since this overview says the main need is for customers to have a way to track things, maybe start with the customer login and don't worry about having a shop login, for now. 

There's kind of two projects here: 1) a way for customers to be able to keep better records of their car service and 2) a way for shops to communicate updates to customers.  Maybe try to do one of those projects really well for the purposes of this 8-week course.

**Comment by Josephstegall** [comment]
addressed
