### ISSUE TITLE
Project outline - Technologies

### ISSUE THREAD

**Issue by r-spell** [Josephstegall/liftoff-assignments#3]
Based on your "need to learn" section, it seems like you might be incorporating more technologies than you listed here. How are you thinking of using React?

You might want to start with jQuery or vanilla JavaScript in order to make it easier to accomplish the project in the timeframe.

The idea of a progress bar sounds cool, but I would try to start with information updates, first. You already know how to make a list from LC101, maybe the list could be updated with the different stages the car is at.

**Comment by Josephstegall** [comment]
Took some technologies out
