### ISSUE TITLE
Project Planning - Project Link

### ISSUE THREAD

**Issue by r-spell** [Josephstegall/liftoff-assignments#4]
Joe, it looks like you've done a lot with planning to have a project you can build in steps.  Love the wire frames.

For the Project tracker, I see you have the user stories in the description.  The standard thing is just to put them for the title.  It's also a lot easier this way 😄 

See how they do it in the demo project tracker https://www.pivotaltracker.com/n/projects/2157573

**Comment by Josephstegall** [comment]
Updated pivotal tracker
